arkivverket/noark5-standard

kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst
metadata/M609.yaml

I metadatakatalogen og i en av to tabeller med oversikt over felter
i journalhode, så var datatypen for antallJournalposter ført opp som
Tekststreng, ikke Heltall.  I den siste tabellen og XSD er datatypen
heltall.
Dette løser en av problemene rapportert i mangelmelding #24.

Datatypen for antallJournalposter skal være Heltall, ikke Tekststreng

---

kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst
metadata/M716.yaml

Henviser til IETF, IANA og PRONOM som kilde til gyldige MIME-typer.
Fixes #35

Opprett M716 mimeType i metadatakatalogen.

---

kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst
kapitler/media/uml-mappestrukturen-diagram.puml
kapitler/media/uml-presedens-diagram.puml
kapitler/media/uml-registrering-diagram.puml

Oppdaterte tillegg B og UML-diagrammer.  I henhold til navnereglene i
Noark 5 skal det være presedensstatus siden det er ett ord.
XSD må også oppdateres.
Fixes #56

Endret M056 presedensStatus til presedensstatus (med liten S) over alt

---

kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst
metadata/M100.yaml
metadata/M101.yaml
metadata/M102.yaml
metadata/M103.yaml
metadata/M104.yaml
metadata/M105.yaml
metadata/M106.yaml
metadata/M107.yaml
metadata/M108.yaml
metadata/M109.yaml
metadata/M110.yaml
metadata/M111.yaml
metadata/M112.yaml
metadata/M113.yaml
metadata/M452.yaml
metadata/M505.yaml
metadata/M617.yaml

Endre samtlige dato til dato med klokkeslett i metadatakatalog
og tillegg B.  Endrer type på M100, M101, M102, M103, M104, M105,
M106, M107, M108, M109, M110, M111, M112, M113, M452, M505 og M617.
Relatert til #24
Fixes #38
Fixes #41
Fixes #42
Fixes #43

Bytt til dato med klokkeslett for alle tidsstempler

---

kapitler/110-vedlegg_1_metadatakatalog-auto.rst
kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst
metadata/M506.yaml

Krav 4.5.21 og 4.5.22 snakker om disse verdiene som graderingskode,
tillegg A og B bruker navnet 'gradering', tjenestegrensesnitt-
spesifikasjonen bruker navnet 'graderingskode' og XSD-skjema bruker
navnet 'grad'.
Bakgrunnen er at det var en liten navnekollisjon, der XSD hadde en
entitet ved navn 'gradering', og en metadatakatalogoppføring ved
navn 'gradering'.  Sistnevnte ble endret til 'grad' i XSD, men ikke
i Noark 5-spesifikasjonen og tjenestegrensesnittet.
Navnet 'grad' kan misforstås til å gjelde temperatur eller vinkel,
mens 'graderingskode' er mer entydig.  Endrer derfor til
'graderingskode' i tillegg A (Metadatakatalog) og B (Metadata
gruppert på objekter).  XSD må endres tilsvarende.
XSD-endringsforslag kan ses på
https://github.com/arkivverket/schemas/issues/13 .

Endret navn på M506 fra 'grad' til 'graderingskode'

---

kapitler/030-noark-5-datamodell.rst
kapitler/110-vedlegg_1_metadatakatalog-auto.rst
metadata/M701.yaml
metadata/M712.yaml
metadata/M713.yaml

I dagens spesifikasjon står det at offisiell liste over formatverdier skal utarbeides og publiseres senere.  De siste årene har Arkivverket formidlet at det skal brukes PRONOM-koder, og det er på tide å få det skrevet inn i Noark 5-spesifikasjonen.  Beskrivelsen er basert på tekst i Noark 5 Tjenestegrensesnitt, og henviser til tillegg D der for å ha et enkelt sted å holde oppdatert med peker til autorativ liste over koder fra Arkivverket.

Klargjør at format-verdier som hovedregel er PRONOM-koder

---

kapitler/030-noark-5-datamodell.rst

Formuleringen ble gjenglemt da basisregistrering og registrering
ble slått sammen.
Fixes #33.

Fjern rest '(unntatt registrering)' fra krav 2.8.3 om nøkkelord.

---

kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst

En av tre oppføringer i tillegg B hadde datatype registrering.systemID,
de to øvrige hadde Tekststreng.  Gjør alle om til registrering.systemID,
slik at det er entydig hvordan en refererer til en journalpost og slik at
tillegg B tilsvarer XSD som har datatype 'ID' for M215.
Relatert til #24.

Samkjør datatype for M215/referanseAvskrivesAvJournalpost

---

kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst
metadata/M707.yaml

Datatypen for dette feltet er allerede heltall i i XSD og Tjenestegrensesnitt, mens tillegg B fortsatt har den oppført som tekststreng.
Endret beskrivelsen samtidig til å ikke nevne desimaltall, som kan tolkes som kommatall, hvilket ikke gir mening for antall bytes. I stedet for å oppgi tallsystem i de ulike numeriske feltene, som antallJournalposter, så er det kanskje bedre å skrive annen plass i teksten at alle heltall skal oppgis i titallsystemet.

Datatypen for filstoerrelse skal være Heltall, ikke Tekststreng

---

kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst

Dette ble gjenglemt fra da metadatakatalogoppføringen endret navn
i 238c7c3aa06f0395b3da06ad0f10712ea656adb4.

Korrigerte navn på M506 graderingskode i journalpost

---

kapitler/070-funksjoner_for_periodiske_oppgaver.rst

Riksarkivarens forskrift sier DOKUMENT/, og Noark 5 sa både
DOKUMENT/ og dokumenter/ før denne endringen.  Byttet ut
dokumenter/ med DOKUMENT/ et sted hvor teksten motsa seg selv.
Fixes #51

Bytt til DOKUMENT/ for fillagring.

---

kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst
metadata/M209.yaml

Flyttet fra saksmappe til mappe og lagt til i registrering.  Dette gjør
det mulig å emneklassifisere både registreringer og journalposter i tillegg
til mappe for enklere søk basert på emnebasert klassifikasjonssystem.
Fixes #40

La referanseSekundaerKlassifikasjon til i mappe og registrering

---

metadata/M037.yaml

Fylkesnummer i objektsortert metadataliste og Noark 5 Tjenestegrensesnitt
er tekststreng, mens den var ført opp som heltall i YAML-filen.  Dette er
de to første tegnene i kommunenummer, som også er tekststreng, så jeg
tror tekstsstreng er korrekt.  Endret derfor YAML-filmen.
Relatert til #53.

Samkjør datatype for M037 fylkesnummer mellom YAML og objektsortert

---

kapitler/070-funksjoner_for_periodiske_oppgaver.rst
kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst

For å kunne hente ut all informasjon i et arkivsystem på en strukturert
måte, og ha fleksibiliteten til å ta vare på flere verdier enn det som
har egne standardiserte felter, så legges det inn støtte for feltet
virksomhetsspesifikkeMetadata på alle arkivenheter som i dag mangler det.
Legges inn i arkiv, arkivdel, klassifikasjonssystem, klasse og
dokumentobjekt.  Dette er en oppfølger til endringsforslag #96 der det
legges inn i dokumentbeskrivelse og korrespondansepart.

La til virksomhetsspesifikkeMetadata for resterende arkivenheter

---

kapitler/030-noark-5-datamodell.rst
kapitler/110-vedlegg_1_metadatakatalog-auto.rst
kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst
metadata/M705.yaml
metadata/M706.yaml
metadata/M717.yaml
metadata/M718.yaml
metadata/M719.yaml
metadata/M720.yaml

Med dagens beskrivelse av konverteringsinformasjon er det ikke
mulig verifisere konverteringskjeder.  Hvis flere konverteringskjeder
er oppgitt, så vil det  ikke være mulig å vite hvilken kjende en gitt
konvertering tilhører.
Et eksempel er et innkommet ODT-dokument, som konverteres til DOCX, så
til PDF og så til PDF/A.  Hvis en så oppdager at DOCX til PDF-konverteringen
feilet og gjør en ny konvertering, så er det kun tidsstemplet som kan brukes
til å forsøke å gjenskape konverteringskjeden.
Ved å ta med sjekksum (M705) til fra- og til-fil i konverteringsoppføringen,
så blir det mulig å identifisere hvilke deler av kjeden som hører sammen
ved å se hvilken fra-fil i en konvertering som har samme sjekksum som
til-fil i en annen konvertering.  Dette vil også kunne brukes til å oppdage …

Legg ved valgfri sjekksummer i konverteringsinformasjonen

---

kapitler/070-funksjoner_for_periodiske_oppgaver.rst

Endret navn på kravtabeller så de samsvarer med overskriften som står foran, fikser issue #31

Juster tabell-overskrifter i del om bevaring og kassasjon for å unngå duplikater

---

kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst

Gjør bruken av nasjonale identifikatorer mer fleksibelt og i tråd med
det som er støttet i Noark 5 tjenestegrensesnitt.  Flytt kobling av nasjonale
identifikatorer fra saksmappe til mappe og registrering, introduser overordnet
type 'nasjonalidentifikator' som foreldretype til matrikkelnummer, byggident,
planident, posisjon og nye personidentifikator og enhetsidentifikator.  Dette
gjør det mulig å koble en eller flere av disse til både dokumenter og saker.
I tillegg gjort det mulig å koble flere personID til en part og
korrespondansepart, slik at det er mulig å registrere flere ulike
ID-typer på samme korrespondansepart, som passnummer og fødselsnummer,
eller fødselsnummer og D-nummer.
Fixes #77

Flytt kobling av nasjonale identifikatorer fra saksmappe til mappe og registrering

---

kapitler/070-funksjoner_for_periodiske_oppgaver.rst
kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst

I Noark 5 Tjenestegrensesnitt er det beskrevet at en kan legge inn
virksomhetsspesifikkeMetadata koblet til korrespondansepart og
dokumentbeskrivelse.  Dette må reflekteres i spesifikasjonen for
Noark 5, slik at informasjonen kan avleveres.

La til virksomhetsspesifikkeMetadata for korrespondansepart og dokumentbeskrivelse

---

metadata/M043.yaml

Endre beskrivelsen av M043 koordinatsystem til å gjøre det klart at
EPSG-koder skal brukes der de eksisterer, og andre koder skal avklares med
Arkivverket før de tas i bruk.  Oppgi lenker til hvor EPSG-koder kan finnes.

Gjør det klart at EPSG-kode brukes i koordinatsystem

---

kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst

Ved generering av XSD fra RST-filene oppdaget jeg at
virksomhetsspesifikkeMetadata for korrespondansepart var koblet til
feil korrespondansepart.  Skulle vært i arkivstruktur.xsd, ikke
loependeJournal.xsd.  Endringen flytter attributten til riktig sted.
Korrigerer feil introdusert i a45425b1a8ac567a20c2e8ae01806d5249fae93a .

Flytt virksomhetsspesifikkeMetadata til korrekt korrespondansepart

---

kapitler/030-noark-5-datamodell.rst
kapitler/060-gjenfinning_innsyn_rapportering.rst

En har overflødig punktum, en har en 'x' på slutten.

Korriger skrivefeil i to kravnummer.

---

metadata/M215.yaml

Objektsortert liste og XSD sier datatypen er systemID, mens YAML-filen
sier tekststreng.  Endret YAML-filen.
Relatert til #24.

Samkjør datatype for M215 i metadatakatalog og objektsorterte metadata.

---

kapitler/060-gjenfinning_innsyn_rapportering.rst
kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst
kapitler/130-vedlegg_3_logg_over_endringer.rst
metadata/M215.yaml
metadata/M231.yaml

Beskrivelsen av M215 (og M214) sier det skal være mulig å koble til en eller
flere journalposter, mens objektbeskrivelsen av avskrivning sier 0-1, dvs
maksimum 1.  Antar metadatabeskrivelsen er feil og endrer denne til å si
'referanse til journalpost' i stedet.
I Noark 5 Tjenestegrensesnitt er det lagt til en ny attributt til avskrivning,
referanseAvskrivesAvKorrespondansepart.  For at denne skal ha noe å referer
til, så må korrespondansepart ha en unik ID.  I Noark 5 Tjenstegrensesnitt
er dette en systemID, og for å kunne avlevere disse verdiene med Noark 5 bør
også Noark 5 ha systemID koblet til korrespondansepart.  For konsistens
legger jeg også på en systemID på part, som strukturelt er identisk med
korrespondansepart.
Fjernet samtidig alle referanser til ubrukt M214 …

Samkjør avskrivning med Noark 5 Tjenstegrensesnitt og rydd i beskrivelser

---

README.rst

Kopierte informasjon om åndsverksvernestatus fra docbook/spesifikasjon.xml til README.rst for å gjøre den enklere å finne også for de som ikke leser PDF-utgaven.

Vis åndsverksvernestatus i README-filen på toppnivå

---

kapitler/130-vedlegg_3_logg_over_endringer.rst

Intensjonen er at listen beskriver minstekravet for logging, ikke et forbud mot å logge mer, og at dette gjelder hva som som minimum skal trekkes ut/avleveres fra et Noark 5-system.

Dokumenter at listen over loggmeldinger skal tolkes som en minimumsliste.

---

kapitler/110-vedlegg_1_metadatakatalog-auto.rst
metadata/M025.yaml

Omtalt feltnavn var for M502, ikke M504.
Takk til Jørgen for å ha oppdaget feilen.
Fixes #157.

Korrigerte skrivefeil i beskrivelse av M025 (M504 -> M502).
